lang = {} local GMarket_Language = lang

GMarket_Language["Sell Weapon"] = "Sell Weapon"
GMarket_Language["Item Name"] = "Item Name: "
GMarket_Language["Item Category"] = "Item Category: "
GMarket_Language["Item Class"] = "Item Class: "
GMarket_Language["Seller ID"] = "Seller ID: seller-"
GMarket_Language["Sell an item"] = "Sell an item"
GMarket_Language["Category"] = "Category: "
GMarket_Language["Price"] = "Price: "
GMarket_Language["Pick Up"] = "Pick Up"
GMarket_Language["Items"] = "Items"
GMarket_Language["Sell"] = "Sell"

GMarket_Language["MailBox"] = "MailBox"
GMarket_Language["Nothing"] = "Nothing, thanks"
GMarket_Language["Hi"] = "Hi, are you interested in something?"

GMarket_Language["Seller"] = "Seller-"
GMarket_Language["Shopping Cart"] = "Your Shopping Cart - $"
GMarket_Language["Empty"] = "Empty"
GMarket_Language["Added"] = "Added: "
GMarket_Language["Welcome"] = "Welcome"
GMarket_Language["Remove"] = "Remove"
GMarket_Language["Purchase all"] = "Purchase all"
GMarket_Language["Add To Cart"] = "Add To Cart"
GMarket_Language["Purchase"] = "Purchase"
GMarket_Language["Weapons"] = "Weapons"
GMarket_Language["Entities"] = "Entities"
GMarket_Language["Shopping Cart"] = "Shopping Cart"
GMarket_Language["Enter GMarket"] = "Enter GMarket"
GMarket_Language["Price: $"] = "Price: $"
GMarket_Language["Sort by"] = "Sort by"
GMarket_Language["Price(Low to high)"] = "Price(Low to high)"
GMarket_Language["Price(High to low)"] = "Price(High to low)"
GMarket_Language["Name(A-Z)"] = "Name(A-Z)"
GMarket_Language["Name(Z-A)"] = "Name(Z-A)"
GMarket_Language["Date(Newer-older)"] = "Date(Newer-older)"
GMarket_Language["Date(Older-newer)"] = "Date(Older-newer)"

GMarket_Language["No money"] = "You do not have enough money"
GMarket_Language["Sold"] = "You just sold a"
GMarket_Language["for"] = "for $"
GMarket_Language["Purchased"] = "Successfully purchased"
GMarket_Language["No available"] = "A item is no longer available"
GMarket_Language["Thank you"] = "Thank you"
GMarket_Language["You already have"] = "You already have "
GMarket_Language["Arrived"] = "Your package has arrived"

GMarket_Language["This is not your mailbox"] = "This is not your mailbox!"

GMarket_Language["Features"] = "Features"
GMarket_Language["Delivery Time"] = "Delivery Time reduced"
GMarket_Language["Items cost"] = "Reduced price for GMarket products"
GMarket_Language["Exclusive items"] = "Exclusive items"
GMarket_Language["GPrime Member"] = "Nice, now you are a GPrime member"
GMarket_Language["Already Member"] = "You are already a GPrime member"
GMarket_Language["Seconds"] = " seconds"

AddCSLuaFile()